name: Deploy to Amazon EKS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: eks-cicd
  ECR_REPOSITORY: education-platform
  K8S_DEPLOYMENT: education-platform
  K8S_CONTAINER: education-platform
  K8S_NAMESPACE: default

jobs:
  deploy:
    name: Build and Deploy to EKS
    runs-on: ubuntu-latest

    steps:

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build and Test
        run: mvn clean package

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::035699610728:role/GitHubActions-EKS-Deploy-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }} \
            .

      - name: Push Docker Image
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region ${{ env.AWS_REGION }} \
            --name ${{ env.EKS_CLUSTER_NAME }}

      - name: Verify EKS Access
        run: |
          kubectl get nodes
          kubectl get deployment \
            ${{ env.K8S_DEPLOYMENT }} \
            -n ${{ env.K8S_NAMESPACE }}

      - name: Deploy New Image
        run: |
          kubectl set image deployment/${{ env.K8S_DEPLOYMENT }} \
            ${{ env.K8S_CONTAINER }}=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }} \
            -n ${{ env.K8S_NAMESPACE }}

      - name: Wait for Rollout
        run: |
          kubectl rollout status \
            deployment/${{ env.K8S_DEPLOYMENT }} \
            -n ${{ env.K8S_NAMESPACE }} \
            --timeout=5m

      - name: Verify Deployment
        run: |
          kubectl get pods -n ${{ env.K8S_NAMESPACE }} -o wide
          kubectl get service -n ${{ env.K8S_NAMESPACE }}